###
GET http://localhost:5024/api/item/viewmenu
###
GET http://localhost:5024/api/table/1/items
###
GET http://localhost:5024/api/tabledetail
###
GET http://localhost:5024/api/tabledetail/1
###
GET http://localhost:5024/api/table
###
GET http://localhost:5024/api/tabledetail
###
GET http://localhost:5024/api/table/reality
###
GET http://localhost:5024/api/table/virtual
###
###
GET http://localhost:5024/api/feedback/items
###
GET  http://localhost:5024/api/account/logout
###
GET http://localhost:5024/api/account/getallacc
###
DELETE  http://localhost:5024/api/account/deleteacc
Content-Type: application/json

{
  "username": "customer1"
}
###
PUT  http://localhost:5024/api/account/status
Content-Type: application/json

{
  "username": "customer2"
}
###
POST  http://localhost:5024/api/account/login
Content-Type: application/json

{
  "Username": "admin_user",
  "Password": "adminpass"
}
###
POST  http://localhost:5024/api/account/addstaff
Content-Type: application/json

{
    "username": "onlyshymran",
    "password": "shyranaway",
    "fullname": "Doraemon Nek",
    "gender": 1,
    "phoneNumber": "0912345678",
    "email": "git.jack1624@gmail.com",
    "address": "DN NHS",
    "RoleDescription": "Food Runner"
}
###
POST  http://localhost:5024/api/account/VerifyCode
Content-Type: application/json

{
  "code": "209946"
}

###
POST  http://localhost:5024/api/account/signup
Content-Type: application/json

{
  "username": "d2r1324",
    "password": "doraemon@123",
    "name": "Doraemon Nek",
    "gender": 1,
    "phoneNumber": "0912345678",
    "email": "git.jack1624@gmail.com",
    "address": "DN NHS",
    "confirmPassword": "doraemon@123",
    "VerificationCode": "null",
    "roleDescription": "null"
}
###
GET http://localhost:5024/api/feedback/allfeedbacks
###
GET http://localhost:5024/api/feedback/item/11
###
POST http://localhost:5024/api/feedback/submitfeedback
Content-Type: application/json

{
  "Content": "12/1/2024 4PM",
  "ItemId": 1,
  "ItemName": "Pizza Margherita",
  "ParentFb": null
}
###
PUT http://localhost:5024/api/feedback
Content-Type: application/json

{
  "Id": 76,
  "Content": "halohalo",
  "ItemId": 1,
  "ItemName": "Pizza Margherita",
  "ParentFb": 16
}
###
GET http://localhost:5024/api/feedback/feedbackpagination?pageNumber=1&pageSize=10
###
DELETE http://localhost:5024/api/feedback/10
###
GET http://localhost:5024/api/feedback/replies/11
###
POST http://localhost:5024/api/feedback/reply
Content-Type: application/json

{
  "Content": "This is a reply message.",
  "ItemId": 1,
  "ItemName": "Pizza Margherita",
  "ParentFb": 19
}
###
PUT http://localhost:5024/api/feedback/reply
Content-Type: application/json

{
  "Id": 57,
  "Content": "Updated reply message.",
  "ItemId": 1,
  "ItemName": "Pizza Margherita",
  "ParentFb": 14
}
###
POST http://localhost:5024/api/account/login
Content-Type: application/json

{
    "username": "customer1",
    "password": "customerpass"
}
###
POST http://localhost:5024/api/account/login
Content-Type: application/json

{
    "username": "jane_smith",
    "password": "password456"
}
###
GET http://localhost:5024/api/feedback/items
###
POST http://localhost:5024/api/account/logout
###
GET http://localhost:5024/api/table
###
GET http://localhost:5024/api/tabledetail
###
GET http://localhost:5024/api/table/reality
###
GET http://localhost:5024/api/table/virtual
###



