@ZetstyBite_HostAddress = https://localhost:5221

POST {{ZetstyBite_HostAddress}}/api/account/signup
Content-Type: application/json

{
    "username": "dotnetlord",
    "password": "StrongP@ssw0rd!",
    "fullName": "hacker lord",
    "phone": "1234567890",
    "address": "123 Elm Street, Springfield",
    "gender": true,
    "email": "daonxemand@gmail.com",
}

###

GET {{ZetstyBite_HostAddress}}/api/account

###

GET http://localhost:5221/api/account/10

###

POST http://localhost:5221/api/account/signup2
Content-Type: application/json

{
    "accountId": 17,
    "username": "neacco7unt19c39",
    "password": "StrongP@ssw0rd!",
    "name": "Hacker Lord Z",
    "phoneNumber": "1234567890",
    "address": "123 Elm Street, Springfield",
    "gender": 0, 
    "email": "dao7z19cz0d@gmail.com",
    "profileImage": "default null",
    "verificationCode": "abc123",
    "role":{
        "roleId": 7,
        "roleDescription": "Customer"
    }
}

###
