###
GET http://localhost:5024/api/feedback/items
###
GET http://localhost:5024/api/feedback/items
###
POST  http://localhost:5024/api/account/login
Content-Type: application/json

{
  "Username": "doraemon12",
  "Password": "doraemon@12"
}
###
POST  http://localhost:5024/api/account/VerifyCode
Content-Type: application/json

{
  "code": "754163"
}
POST  http://localhost:5024/api/account/VerifyCode
Content-Type: application/json

{
  "code": "754163"
}

###
POST  http://localhost:5024/api/account/signup
Content-Type: application/json

{
  "username": "dr1212z",
    "password": "doraemon@123",
  "username": "dr1212z",
    "password": "doraemon@123",
    "name": "Doraemon Nek",
    "gender": 1,
    "phoneNumber": "0912345678",
    "email": "git.jack1624@gmail.com",
    "email": "git.jack1624@gmail.com",
    "address": "DN NHS",
    "confirmPassword": "doraemon@123",
    "confirmPassword": "doraemon@123",
    "roleDescription": "null"
}
###
GET http://localhost:5024/api/feedback/allfeedbacks
###
GET http://localhost:5024/api/feedback/item/11
###
POST http://localhost:5024/api/feedback/submitfeedback
Content-Type: application/json

{
  "Content": "12/1/2024 4PM",
  "Username": "jane_smith",
  "ItemId": 1,
  "ItemName": "Pizza Margherita",
  "ParentFb": null
}
###
PUT http://localhost:5024/api/feedback
Content-Type: application/json

{
  "Id": 58,
  "Content": "halohalo",
  "ItemId": 1,
  "ItemName": "Pizza Margherita",
  "ParentFb": 16
}
###
GET http://localhost:5024/api/feedback/feedbackpagination?pageNumber=1&pageSize=10
GET http://localhost:5024/api/feedback/feedbackpagination?pageNumber=1&pageSize=10
###
DELETE http://localhost:5024/api/feedback/57
###
GET http://localhost:5024/api/feedback/replies/11
###
POST http://localhost:5024/api/feedback/reply
Content-Type: application/json

{
  "Content": "This is a reply message.",
  "ItemId": 1,
  "ItemName": "Pizza Margherita",
  "ParentFb": 16
}
###
PUT http://localhost:5024/api/feedback/reply
Content-Type: application/json

{
  "Id": 57,
  "Content": "Updated reply message.",
  "ItemId": 1,
  "ItemName": "Pizza Margherita",
  "ParentFb": 14
}
###
POST http://localhost:5024/api/account/login
Content-Type: application/json

{
    "username": "jane_smith",
    "password": "password456"
}
###

###

###

###

###


########################################################################
