@ZestyBiteWebAppSolution_HostAddress = https://localhost:7131

###
POST http://localhost:7131/api/feedback
Content-Type: application/json

{
    "content": "awd awd awd wad ",
    "dateTime": "2024-11-21T15:14:00",
    "accountId": 1,
    "username": "john_doe",
    "profileImage": null,
    "itemId": 1,
    "itemName": "Pizza Margherita"
}
###
GET http://localhost:7131/api/feedback/all
###
GET http://localhost:7131/api/feedback/allpage?pageNumber=1&pageSize=10
###
GET http://localhost:7131/api/feedback/item/6
###
DELETE http://localhost:7131/api/feedback/1
###

###

###

###

###

###
